# Configuration file for training a deep learning model (Classifier MLP and Autoencoder models)

trainer:
  optimizer: "Adam"
  lr: 0.001
  batch_size: 1024
  epochs: 20
  device: "cpu"
  weight_decay: 0.0001
  threshold: 0.5
  early_stopping:
    patience: 5

Loss:
  type: "BCEWithLogitsLoss"
  pos_weight: "(negative_samples / positive_samples)" # For TRAIN only"
